/*
 * Video Telemetry for Mountain Bike Platform back-end services.
 * Copyright (C) 2017 Kyle Grund
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.vitembp.embedded.gui800x480;

import com.vitembp.embedded.configuration.SystemConfig;

/**
 *
 * @author kgrund
 */
public class OptionsMenu extends javax.swing.JDialog {

    /**
     * Creates new form CaptureStatus
     */
    public OptionsMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // update system ID
        this.jLabelSystemID.setText(SystemConfig.getConfig().getSystemUUID().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelNavBar = new javax.swing.JPanel();
        captureStatusButton = new javax.swing.JButton();
        captureSetupButton = new javax.swing.JButton();
        networkingButton = new javax.swing.JButton();
        optionsButton = new javax.swing.JButton();
        jPanelNavigation = new javax.swing.JPanel();
        quitButton = new javax.swing.JButton();
        jPanelSystemID = new javax.swing.JPanel();
        jLabelSystemID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 480));
        setName("captureStatus"); // NOI18N
        setUndecorated(true);

        jPanelNavBar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        captureStatusButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        captureStatusButton.setText("Capture Status");
        captureStatusButton.setMaximumSize(new java.awt.Dimension(193, 50));
        captureStatusButton.setMinimumSize(new java.awt.Dimension(193, 50));
        captureStatusButton.setPreferredSize(new java.awt.Dimension(193, 50));
        captureStatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captureStatusButtonActionPerformed(evt);
            }
        });
        jPanelNavBar.add(captureStatusButton);

        captureSetupButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        captureSetupButton.setText("Capture Setup");
        captureSetupButton.setMaximumSize(new java.awt.Dimension(193, 50));
        captureSetupButton.setMinimumSize(new java.awt.Dimension(193, 50));
        captureSetupButton.setPreferredSize(new java.awt.Dimension(193, 50));
        jPanelNavBar.add(captureSetupButton);

        networkingButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        networkingButton.setText("Networking");
        networkingButton.setMaximumSize(new java.awt.Dimension(193, 50));
        networkingButton.setMinimumSize(new java.awt.Dimension(193, 50));
        networkingButton.setPreferredSize(new java.awt.Dimension(193, 50));
        jPanelNavBar.add(networkingButton);

        optionsButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        optionsButton.setText("Options");
        optionsButton.setMaximumSize(new java.awt.Dimension(193, 50));
        optionsButton.setMinimumSize(new java.awt.Dimension(193, 50));
        optionsButton.setPreferredSize(new java.awt.Dimension(193, 50));
        jPanelNavBar.add(optionsButton);

        jPanelNavigation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Navigation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        quitButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelNavigationLayout = new javax.swing.GroupLayout(jPanelNavigation);
        jPanelNavigation.setLayout(jPanelNavigationLayout);
        jPanelNavigationLayout.setHorizontalGroup(
            jPanelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelNavigationLayout.setVerticalGroup(
            jPanelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelNavigationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(quitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jPanelSystemID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "System ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabelSystemID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelSystemID.setText("00000000-0000-0000-0000-000000000000");

        javax.swing.GroupLayout jPanelSystemIDLayout = new javax.swing.GroupLayout(jPanelSystemID);
        jPanelSystemID.setLayout(jPanelSystemIDLayout);
        jPanelSystemIDLayout.setHorizontalGroup(
            jPanelSystemIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSystemIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSystemID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSystemIDLayout.setVerticalGroup(
            jPanelSystemIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelSystemID)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelNavBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelSystemID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelSystemID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jPanelNavBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // quit button exits program
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void captureStatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captureStatusButtonActionPerformed
        // show capture status
        GUI.showCaptureControl();
    }//GEN-LAST:event_captureStatusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OptionsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OptionsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OptionsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OptionsMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OptionsMenu dialog = new OptionsMenu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton captureSetupButton;
    private javax.swing.JButton captureStatusButton;
    private javax.swing.JLabel jLabelSystemID;
    private javax.swing.JPanel jPanelNavBar;
    private javax.swing.JPanel jPanelNavigation;
    private javax.swing.JPanel jPanelSystemID;
    private javax.swing.JButton networkingButton;
    private javax.swing.JButton optionsButton;
    private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables
}
